const projectData = [
  {
    id: 'blackandwhite',
    title: "проект Черное на белом",
    services: 'Технический и интерьерный дизайн',
    type: 'Квартира',
    area: "64 м²",
    image: "/images/pr1/1.jpg",
    gallery: [
      "/images/pr1/2.jpg",
      "/images/pr1/4.jpg",
      "/images/pr1/5.jpg",
      "/images/pr1/6.jpg",
      "/images/pr1/7.jpg",
    ],
  },
  {
    id: 'bergamot',
    title: "проект Бергамот",
    services: 'Технический и интерьерный дизайн',
    type: 'Квартира',
    image: "/images/pr2/02.jpg",
    area: '58 м²',
    gallery: [
      "/images/pr2/01.jpg",
      "/images/pr2/02.jpg",
      "/images/pr2/03.jpg",
      "/images/pr2/04.jpg",
      "/images/pr2/05.jpg",
      "/images/pr2/06.jpg",
      "/images/pr2/07.jpg",
      "/images/pr2/09.jpg",
      "/images/pr2/08.jpg",
      "/images/pr2/10.jpg",
      ],
  },
  {
    id: 'etnos',
    title: "проект Этнос",
    services: 'Технический и интерьерный дизайн',
    type: 'Квартира',
    area: "72 м²",
    image: "/images/pr4/03.jpg",
    gallery: [
      "/images/pr4/01.jpg",
      "/images/pr4/02.jpg",
      "/images/pr4/03.jpg",
      "/images/pr4/04.jpg",
      "/images/pr4/05.jpg",
      "/images/pr4/06.jpg",
      "/images/pr4/07.jpg",
      "/images/pr4/08.jpg",
      "/images/pr4/09.jpg",
      "/images/pr4/10.jpg",
      "/images/pr4/11.jpg",
      "/images/pr4/12.jpg",
      "/images/pr4/13.jpg",
      
      ],
  },
  {
    id: 'balans',
    title: "проект Баланс",
    area: "98 м²",
    services: 'Технический и интерьерный дизайн',
    type: 'Коттедж',
    image: "/images/pr3/03.jpg",
    gallery: [
        "/images/pr3/01.jpg",
      "/images/pr3/02.jpg",
      "/images/pr3/03.jpg",
      "/images/pr3/04.jpg",
      "/images/pr3/05.jpg",
      "/images/pr3/06.jpg",
      "/images/pr3/07.jpg",
      "/images/pr3/08.jpg",
      "/images/pr3/09.jpg",
      "/images/pr3/10.jpg",
      "/images/pr3/11.jpg",
      "/images/pr3/12.jpg",
      "/images/pr3/13.jpg",
      "/images/pr3/14.jpg",
      "/images/pr3/15.jpg",
      "/images/pr3/16.jpg",
      "/images/pr3/17.jpg",
      "/images/pr3/18.jpg",
      ],
  },
  {
    id: 'teplmin',
    title: "проект Теплый минимализм",
    services: 'Технический и интерьерный дизайн',
    type: 'Квартира',
    area: "54 м²",
    image: "/images/pr5/02.jpg",
    gallery: [
        "/images/pr5/01.jpg",
        "/images/pr5/02.jpg",
        "/images/pr5/03.jpg",
        "/images/pr5/04.jpg",
        "/images/pr5/05.jpg",
        "/images/pr5/06.jpg",
        "/images/pr5/07.jpg",
        "/images/pr5/09.jpg",
        "/images/pr5/08.jpg",
        "/images/pr5/10.jpg",
      ],
  },
];

export default projectData;
